import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <head>
          <title>Nenes Product App</title>
          <link rel="icon" href="https://i.ibb.co/qjvp9L7/8405d0b564e86a7ba13fe5ade52cca7d-cubo-amarillo-plano.png" />
        </head>
        <body className={inter.className}>
          <Navbar />
          {children}
          <Footer/>
        </body>
      </html>
    </>
  );
}
